### PR TITLE
Added withRegion.

### PR DESCRIPTION
**Pull request by phaazon**
`withRegion` introduces nested regions as we can run a `R q a` action
in `R s a` action with `q <= s`. I made basic test on the nesting
property, even though I haven’t found a way – yet? – to test whether
the resources are correctly freed and released – even though the deepseq
should help to ensure that.

### CODE REVIEW

**Comment by phaazon** [comment]
Hm, the error is due to the GHC version. I’ll fix that.

**Comment by mboes** [comment]
Thanks for the contribution. :)

Let's agree on the spec for `withRegion`. We want:

1. to make it possible to create a new region from within the dynamic scope of any existing region,
1.  to "unprotect" all objects allocated during the dynamic scope of the subregion at exactly the point at which the subregion is exited;
1. to demote resources in parent regions to resources in the subregion (i.e. subregions can access both objects allocated in its scope and also any encompassing scope).

The current implementation of `withRegion` satisfies (1) but not (2). To satisfy (2), you need to do much the same thing as `runRegion`: carry around an IORef that gets incremented at each allocation, and then unprotect that many objects when the region exits. As for (3) we need another pair of functions, called say

```Haskell
demote :: (s <= q) => SEXP q a -> SEXP s a
demoteSome :: (s <= q) => SomeSEXP q -> SomeSEXP s
```

One way to write a test for (2) is to register a finalizer using R's `reg.finalizer()` function, then calling `gc()` to force a garbage collection, and checking whether the finalizer was called (say by having the finalizer mutate some shared MVar upon execution).

**Comment by qnikst** [comment]
@phaazon 
As for (3). In order to write a nested region you need to keep the Region stack explicitly, i.e. `R` region should be parametrized by it's ancestors [2]. Using this form you'll induce `<=` relation between regions. Is such regions you'll be able to use `demote` really we already have this function it's called `release` [3] (yet no `releaseSome` equivalent.

For the work you are doing we already had done some amount of work, see `nested` branch [1], however it's was written more that a year ago, many things in project changed since that time, and this work was not approved by all the team (mainly because there were no need in nested regions that time). So you could grab some ideas, but do not forget to check that fits current design and spec that @mboes provided, I think it's a great explanation of that we want. Especially be careful in the place where you may want to return R values from nested region, though I suppose current design made this place smooth enough.

Few notes from me.
In tests please test "monadic" operation, because in your current test `fromSEXP` clears all information about region, so you could easily mix values, even if it's should not be allowed, I hope in `nested` branch nice example still left.
Also it's nice to use different values in all entries in test, otherwise you may miss certain types of errors. For example consider your second test, suppose that you have a bug and R could deallocate `x` while you are in nested region, then when you allocate `y` in could be allocated in a place where `x` was (due to properties of R memory allocation), then when you will be reading values, you'll read `y` 2 times, but because `x` is equal to `y` you'll never notice that, and test will always succeed.
As for testing if value is protected or not, see example:
https://github.com/tweag/HaskellR/blob/master/inline-r/tests/Test/GC.hs#L32-L39
In order to test this well you may want to read about R memory model (and possibly bring better ideas than we have), but what we are using:
1. `[r| gctorture(TRUE) |]` this comman enables torture mode (sometimes you need gctorture2),
this function calls GC on each allocation (see R's help for more information on this function)
2. In a place where you want to check if some memory was retained or not, you could allocate something `_ <- io $ R.allocList 1`, then if you value was not protected and was GC-ed, then the type of the value will be `Nil`
3. after the end of the test set `[r| gctorture(FALSE)|]` otherwise R will be too slow.
We have such kind of tests, just grep `gctorture` in the project.

I hope it will help.

A bit unrelated.  if you are more interested in lightweight regions you could read Oleg Kiselyov work  http://okmij.org/ftp/Haskell/regions.html , but please note that due to the difference of the R model this regions have few differences comparing to the original implementation though they have equal expressiveness.

[1] https://github.com/tweag/HaskellR/tree/nested
[2] https://github.com/tweag/HaskellR/blob/nested/src/Control/Memory/Region.hs#L42-L47
[3] https://github.com/tweag/HaskellR/blob/master/inline-r/src/Foreign/R.chs#L227-L231

**Comment by phaazon** [comment]
Thanks. I read the paper from Oleg Kiselyov a few months ago and have been used to that kind of regions. Thanks for your great comment ;)

**Comment by mboes** [comment]
Superseded by #222.

**Pull request closed without merging**
