### PR TITLE
Add regression tests for R_LIBS env

### PR DESCRIPTION
**Pull request by bezirg**
This was after the request of @facundominguez . I had difficulty in creating these tests because: a) i am not well-versed in R and b) i wasn't sure what tests are meaningful here. Feel free to merge or even reject/close this PR.

### CODE REVIEW

**Comment by bezirg** [comment]
Also, the reason I use separate tests executables is that I am testing `populateEnv` via `initialize`: `initialize` can only be called once per process.

**Comment by mboes** [comment]
I defer to @facundominguez on whether the test is worth the weight. Thanks for giving this a crack @bezirg!

**Comment by facundominguez** [comment]
Thanks @bezirg. A variation that would reduce the weight is to have some test print the value of `.libPaths()` or `R_LIBS` in an existing test suite. 

Then a script could run the test suite in CI by only executing the given test with different variable environments.

One other thing that might be worth testing is that `R_LIBS_SITE` is honored.

**Comment by ConnorBaker** [comment]
Hi! Apologies for the delay, I'm the new maintainer of HaskellR.

@facundominguez are there any reasons that this shouldn't be merged as it is right now? I'm open to making some issues to track future work if there are improvements you'd like to see.

**Review by ConnorBaker — APPROVED** [review]

**Comment by ConnorBaker** [comment]
Thank you for your contribution @bezirg!

**Pull request merged**
