### PR TITLE
Build with aeson-2

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by facundominguez** [comment]
The failure in macos is very similar to the one obtained when omitting `-fno-ghci-sandbox` in ghci:
https://tweag.github.io/HaskellR/docs/faq.html

However, this failure occurs when building a module with `ghc` now, and I don't know how to fix it.

**Comment by idontgetoutmuch** [comment]
> The failure in macos is very similar to the one obtained when omitting `-fno-ghci-sandbox` in ghci: https://tweag.github.io/HaskellR/docs/faq.html
> 
> However, this failure occurs when building a module with `ghc` now, and I don't know how to fix it.

I got this also on ghc 8.10.7 but not on 8.10.4. Presumably we should report it to ghc. @facundominguez are you able to do that?

**Comment by facundominguez** [comment]
I'm trying CI with ghc-8.10.4. I'm afraid that reporting anything useful to ghc would require someone to investigate the cause of the error and determine that there is indeed something to fix in ghc. This is not something I can undertake right now.

**Comment by idontgetoutmuch** [comment]
@facundominguez we should at least let them know? Maybe we could at least try with ghc 9? If it fixes itself then we won't have to do anything.

**Comment by facundominguez** [comment]
ghc-8.10.4 did indeed passed CI. We could ask ghc devs if there are any peculiarities in how ghc handles the interpreter thread in macos.

But note that this is no ghc panic, it is message error produced by R, so I'm rather skeptical that a ghc dev will be in good position to figure it out.

**Comment by facundominguez** [comment]
Here's an experiment with ghc-8.10.6. It fails in the same way as ghc-8.10.7:
https://github.com/tweag/HaskellR/runs/4224936110?check_suite_focus=true
https://github.com/tweag/HaskellR/compare/fd/ghc8106

I also sent a question to the ghc-devs list:
https://mail.haskell.org/pipermail/ghc-devs/2021-November/020385.html

**Pull request merged**
