### PR TITLE
Improve ihaskell-inline-r file

### PR DESCRIPTION
**Pull request by qnikst**
* Fix cabal check warnings
* List extensions in cabal file

### CODE REVIEW

**Comment by qnikst** [comment]
Side effect of this commit should be a fix of the -fPIC problem (#213). Can you verify if fixes are working for you, as you were able to reproduce problem.

**Comment by mboes** [comment]
> Can you verify if fixes

who's "you"? Who did you mean to mention?

**Comment by mboes** [comment]
@qnikst any explanation why this seemingly benign cleanup has any incidence on #213?

**Comment by qnikst** [comment]
> who's "you"? Who did you mean to mention?
I wanted @YPares to verify that, because he had setup that allow to check #213.

The reason why this patch affecting -fPIC problem is because it adds `other-extentions: TemplateHaskell`, that forces cabal to build package properly.

**Comment by YPares** [comment]
@qnikst Okay, I got my old setup again, but actually it doesn't allow to reproduce the build.
So I built a new Docker image as @ooblahman is presenting on issue #213, so based on `fpco/stack-build:lts-3.7`
But there is the problem that IHaskell cannot be built right now against lts-3.XX, because some types have changed:
```[19 of 22] Compiling IHaskell.Eval.Evaluate ( src/IHaskell/Eval/Evaluate.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/IHaskell/Eval/Evaluate.o )
    
    src/IHaskell/Eval/Evaluate.hs:195:66:
        Couldn't match expected type ‘[Char]’
                    with actual type ‘Maybe String’
        In the second argument of ‘isPrefixOf’, namely ‘idString’
        In the first argument of ‘guard’, namely
          ‘(iHaskellPkgName `isPrefixOf` idString)’```
So yes, the -fPIC build failure is reproduced when using an image based on lts-3.XX, but this PR is not applicable until IHaskell is updated.

**Pull request merged**
