### PR TITLE
Drop tests in H package.

### PR DESCRIPTION
**Pull request by qnikst**
Tests in H package are not useful, because they do not add
additional test coverage over tests that are in inline-r.
Also those tests are quite hard to automate for different
workflows, as we need to expose correct working directory,
executable name and ghc package directory and it's not
easy to automate withing test itself.

### CODE REVIEW

**Comment by qnikst** [comment]
This commit should address issue #259. Minor version bump will be needed to update version on hackage.

**Comment by mboes** [comment]
Please don't include version bumps as part of patches. That's for the maintainer to manage.

**Comment by qnikst** [comment]
Oh.. sorry this was accidental.

**Comment by qnikst** [comment]
Updated PR to not include version bump.

**Pull request merged**
