### PR TITLE
Bumps for GHC 9.8, fix building with unix-2.8, update CI

### PR DESCRIPTION
**Pull request by andreasabel**
- inline-r/tests: Fix build error with unix-2.8.0
- CI workflow: fix deprecation warnings, bump action versions
- Bump dependencies for GHC 9.8, add latest stackage resolvers

Triggered by:
- https://github.com/commercialhaskell/stackage/issues/7031

### CODE REVIEW

**Comment by facundominguez** [comment]
Hello @andreasabel! Thanks for your patch. I guess some fiddling with the CI configuration is going to be necessary to get this PR in mergeable form. Someone will pick it up eventually if you don't get to it first.

**Comment by andreasabel** [comment]
@facundominguez Yeah, I usually fix CIs, but none that involve nix because I know nothing about nix.

**Comment by ConnorBaker** [comment]
So sorry you're running into this issue with CI! I definitely let it go too long without an update.

I've started work to fix that in https://github.com/tweag/HaskellR/pull/422. I hope to get it merged soon.

Depending on how much bandwidth you have, you can rebase once that happens (should mostly involve just removing the changes you had to make to CI) or I can edit it and commit for you. Let me know which you prefer!

**Comment by andreasabel** [comment]
@ConnorBaker Thanks for taking up the fight with the CI.
I suppose after your PR has been merged, a maintainer can merge mine, resolving the conflicts.

**Comment by ConnorBaker** [comment]
Closing in favor of #422 and #423.

@andreasabel would you make sure those fix the issues you found? Barring GitHub timeout errors, CI should be green for both of those PRs, including the testing on the nightly Stackage snapshot introduced in #423.

**Comment by andreasabel** [comment]
@ConnorBaker thanks!

`cabal build -w ghc-9.8.1` of `inline-r` from `master` went fine.  
`cabal test` reports an error:
``` 
Test suite test-shootout: RUNNING...
During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
Quoted shootout programs
  tests/shootout/binarytrees.R:       During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
Test suite test-shootout: FAIL
```

Not sure whether you want to fix this.
Anyway, once you release to Hackage you can enable `inline-r` in Stackage again.

**Comment by andreasabel** [comment]
Have `cabal` and `ghc` (which is `ghc-9.8.1`) in the PATH.
```
$ echo $LANG

$ R --version
R version 4.3.2 (2023-10-31) -- "Eye Holes"
```
I am on macOS 12, not clear how to get the version of `glibc` there...

**Comment by ConnorBaker** [comment]
Can you try using an older version of R, from the 4.2.x series? I think there may have been a change in 4.3.x which broke some interop.

**Comment by andreasabel** [comment]
Mmh, `brew` does not offer a formula for `R@4.2.3` or similar, and it is a bit much hassle to do a manual install.  (After all, I am not really a user of R...)

**Pull request closed without merging**
